# Файл должен начинаться с тега версии. Используем последнюю.
version: '3'
services:
  postgres:
    image: postgres:13-alpine
    container_name: postgres_movies
    env_file:
      - db.env
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    ports:
      # Перенаправляем запросы, поступающие к localhost:8010 на порт 8010.
      - "5432:5432"
    networks:
      - movies_network

  django:
    build:
      context: .
    container_name: django_movies
    env_file:
      - django.env
    volumes:
      - static_volume:/data/static
    depends_on:
      - postgres
    ports:
      # Перенаправляем запросы, поступающие к localhost:8010 на порт 8010.
      - "8010:8010"
    networks:
      - movies_network

  nginx:
#    image: nginx:1.19.2
    image: nginx:1.21
#    image: blabla_nginx

    container_name: nginx_movies
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs:/etc/nginx/conf.d:ro
    depends_on:
      - django
    ports:
      - "80:80"
    networks:
      - movies_network



# Указываем Docker, какие именованные тома потребуются сервисам
volumes:
  postgres_volume:
  static_volume:

networks:
  movies_network:

